name: 'Check status test'
on:
  push

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Update check status 
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --fail \
        --data '{
          "state": "pending",
          "description": "Waiting for PR deploy",
          "context": "E2E tests"
          }'